apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-web-content
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: /home/farmache/minikube-devops/web-static
